name: advicer
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.0.4
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  get_it: ^7.2.0

dev_dependencies:
  test: ^1.21.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  platform: ^3.1.0
  file: ^6.1.2


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

